require "capybara"
require "rspec"
require "rspec"
require "cucumber"
require "httparty"
require "httparty/request"
require "httparty/response/headers"
require "report_builder"
require "allure-cucumber"

